// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace EcomEngine.DataMigration.EcomEngineDbMigrations
{
    [DbContext(typeof(EcomEngineDb))]
    partial class EcomEngineDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EcomEngine.Business.Common.Entities.EmailTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("BccAddress");

                    b.Property<DateTime?>("DateDeleted");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("DeletionReason");

                    b.Property<string>("EmailLabel");

                    b.Property<Guid?>("EmailTemplateId");

                    b.Property<string>("EmailType");

                    b.Property<string>("FromAddress");

                    b.Property<bool>("IsDefault");

                    b.Property<bool>("LoadDrafts");

                    b.Property<string>("Subject");

                    b.Property<string>("TemplateText");

                    b.Property<int>("VersionCount");

                    b.HasKey("Id");

                    b.HasIndex("EmailTemplateId");

                    b.ToTable("EmailTemplates");
                });

            modelBuilder.Entity("EcomEngine.Business.Common.Entities.EmailTemplate", b =>
                {
                    b.HasOne("EcomEngine.Business.Common.Entities.EmailTemplate")
                        .WithMany("Versions")
                        .HasForeignKey("EmailTemplateId");
                });
#pragma warning restore 612, 618
        }
    }
}
